### ISSUE TITLE
Slight issue with using multiple keys for movement

### ISSUE THREAD

**Issue by devnocs** [PendragonGame/pendragon#136] opened 2017-10-30 21:40 UTC
So, if im holding S and press A or D, it doesn't respond by switching the direction of movement but this works when i'm holding A or D and press any other key. Slight glitch that can be looked into

**Comment by anand-bala** [comment] 2017-11-01 18:28
This is a duplicate of #130. Thanks for the feedback though. 🦄

**Closed as completed by anand-bala** 2017-11-01 18:28 UTC
Labels: duplicate
